name: tf-exp-01
on:
  push:
    branches:
      - tf
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: cml
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          TB_CREDENTIALS: ${{ secrets.TB_CREDENTIALS }}
        run: |
          pip install -r requirements.txt
          python ./src/models/train_model.py
          cml tensorboard connect --logdir=./logs --title=Training --md >> report.md
          cml-send-comment report.md