name: tf-exp-01
on:
  push:
    branches:
      - tf
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - name: Train and Report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TB_CREDENTIALS: ${{ secrets.TB_CREDENTIALS }}
        run: |
          pip install -r requirements.txt
          cml-tensorboard-dev --logdir logs --md --name "Go to tensorboard" >> report.md
          cml-send-comment report.md
          python ./src/models/train_model.py