name: dev-bac
on:
  push:
    branches:
      - dev-bac
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: |
          pip install -r requirements.txt
          python ./src/models/train_model.py
 
          # Create CML report
          #cat ./artifacts/metrics/BaggingClassifier/metrics.txt >> report.md
          echo '![](./artifacts/metrics/BaggingClassifier/plot.png "Confusion Matrix")' >> report.md
          cml comment create report.md
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

