name: tf-exp-01
on:
  push:
    branches:
      - tf
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: |
          pip install -r requirements.txt
          python ./src/models/train_model.py  # generate plot.png
 
          # Create CML report
          cml publish accuracy.png --md --title 'Accuracy' >> report.md
          cml publish loss.png --md --title 'Loss' >> report.md
          cml send-comment report.md
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}